id: 2c247864b22f48f1a415dd2f1fbe6c12
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_308-Questions_Regarding_Death_and_Transmigration-v2
  language: en
  author: ''
  volume: {}
